-- ═══════════════════════════════════════════════════════════════════════════════
-- PharmaInsight Platform — Supabase Schema v3
-- ═══════════════════════════════════════════════════════════════════════════════
--
-- Complete schema with all 7 tables, Row-Level Security policies, auto-profile
-- trigger, and performance indexes.
--
-- Tables:
--   1. user_profiles        — Links to Supabase Auth users
--   2. interaction_reports  — Drug-herb interaction reports
--   3. pharmacology_reports — Pharmacology analysis reports
--   4. saved_reports        — User bookmarked/saved reports
--   5. search_history       — Search history records
--   6. cached_queries       — API response cache (service-role only)
--   7. scientific_synonyms  — Synonym lookup table for normalization
--
-- Usage:
--   Run this entire script in the Supabase SQL Editor (or via supabase db push).
--   The script is idempotent — it uses IF NOT EXISTS / OR REPLACE where possible.
-- ═══════════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════════
-- 1. USER_PROFILES
-- ═══════════════════════════════════════════════════════════════════════════════
-- Extends Supabase Auth users with application-level profile data.
-- One row per auth.users entry; auto-created on signup via trigger below.

CREATE TABLE IF NOT EXISTS user_profiles (
  id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email       TEXT UNIQUE NOT NULL,
  display_name TEXT,
  created_at  TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE user_profiles IS 'Application-level user profiles linked 1:1 to Supabase Auth users.';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_user_profiles_email ON user_profiles(email);

-- RLS
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Users can only read their own profile
CREATE POLICY "Users can read own profile"
  ON user_profiles FOR SELECT
  USING (id = auth.uid());

-- Users can only update their own profile
CREATE POLICY "Users can update own profile"
  ON user_profiles FOR UPDATE
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());


-- ═══════════════════════════════════════════════════════════════════════════════
-- 2. INTERACTION_REPORTS
-- ═══════════════════════════════════════════════════════════════════════════════
-- Stores drug-herb interaction reports generated by the search engine.
-- user_id is nullable to support anonymous (unauthenticated) reports.

CREATE TABLE IF NOT EXISTS interaction_reports (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  drug_name         TEXT NOT NULL,
  herb_name         TEXT NOT NULL,
  interaction_type  TEXT,
  severity          TEXT,
  mechanism         TEXT,
  confidence_score  INTEGER DEFAULT 0,
  evidence_level    TEXT,
  ref_list          JSONB DEFAULT '[]'::jsonb,
  study_results     JSONB DEFAULT '[]'::jsonb,
  fda_data          JSONB,
  sources_used      JSONB DEFAULT '[]'::jsonb,
  evidence_breakdown JSONB DEFAULT '{}'::jsonb,
  top_citation_count INTEGER DEFAULT 0,
  total_studies     INTEGER DEFAULT 0,
  created_at        TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE interaction_reports IS 'Drug-herb interaction reports. user_id is NULL for anonymous submissions.';

-- Indexes — cover common query patterns (by user, by drug+herb, recent first)
CREATE INDEX IF NOT EXISTS idx_interaction_reports_user_id     ON interaction_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_interaction_reports_drug_herb   ON interaction_reports(drug_name, herb_name);
CREATE INDEX IF NOT EXISTS idx_interaction_reports_created     ON interaction_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_interaction_reports_severity    ON interaction_reports(severity);
CREATE INDEX IF NOT EXISTS idx_interaction_reports_evidence    ON interaction_reports(evidence_level);

-- RLS
ALTER TABLE interaction_reports ENABLE ROW LEVEL SECURITY;

-- Anyone can read interaction reports (public knowledge base)
CREATE POLICY "Public read interaction reports"
  ON interaction_reports FOR SELECT
  USING (true);

-- Authenticated users can insert their own reports
CREATE POLICY "Users insert own interaction reports"
  ON interaction_reports FOR INSERT
  WITH CHECK (user_id = auth.uid() OR user_id IS NULL);

-- Users can update only their own reports
CREATE POLICY "Users update own interaction reports"
  ON interaction_reports FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Users can delete only their own reports
CREATE POLICY "Users delete own interaction reports"
  ON interaction_reports FOR DELETE
  USING (user_id = auth.uid());


-- ═══════════════════════════════════════════════════════════════════════════════
-- 3. PHARMACOLOGY_REPORTS
-- ═══════════════════════════════════════════════════════════════════════════════
-- Stores pharmacology analysis reports for herbal compounds.
-- user_id is nullable to support anonymous submissions.

CREATE TABLE IF NOT EXISTS pharmacology_reports (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  compound_name          TEXT NOT NULL,
  herb_name              TEXT NOT NULL,
  mechanisms             JSONB DEFAULT '[]'::jsonb,
  active_compounds       JSONB DEFAULT '[]'::jsonb,
  pharmacological_actions JSONB DEFAULT '[]'::jsonb,
  evidence_score         INTEGER DEFAULT 0,
  evidence_level         TEXT,
  confidence             TEXT,
  ref_list               JSONB DEFAULT '[]'::jsonb,
  sources_used           JSONB DEFAULT '[]'::jsonb,
  created_at             TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE pharmacology_reports IS 'Pharmacology analysis reports for herbal compounds. user_id is NULL for anonymous submissions.';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_pharmacology_reports_user_id    ON pharmacology_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_pharmacology_reports_herb       ON pharmacology_reports(herb_name);
CREATE INDEX IF NOT EXISTS idx_pharmacology_reports_compound   ON pharmacology_reports(compound_name);
CREATE INDEX IF NOT EXISTS idx_pharmacology_reports_created    ON pharmacology_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pharmacology_reports_evidence   ON pharmacology_reports(evidence_level);

-- RLS
ALTER TABLE pharmacology_reports ENABLE ROW LEVEL SECURITY;

-- Anyone can read pharmacology reports
CREATE POLICY "Public read pharmacology reports"
  ON pharmacology_reports FOR SELECT
  USING (true);

-- Authenticated users can insert their own reports
CREATE POLICY "Users insert own pharmacology reports"
  ON pharmacology_reports FOR INSERT
  WITH CHECK (user_id = auth.uid() OR user_id IS NULL);

-- Users can update only their own reports
CREATE POLICY "Users update own pharmacology reports"
  ON pharmacology_reports FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Users can delete only their own reports
CREATE POLICY "Users delete own pharmacology reports"
  ON pharmacology_reports FOR DELETE
  USING (user_id = auth.uid());


-- ═══════════════════════════════════════════════════════════════════════════════
-- 4. SAVED_REPORTS
-- ═══════════════════════════════════════════════════════════════════════════════
-- User bookmarks / saved reports. Each row links a user to a specific
-- interaction or pharmacology report they want to revisit.

CREATE TABLE IF NOT EXISTS saved_reports (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  report_id       TEXT NOT NULL,
  report_type     TEXT NOT NULL CHECK (report_type IN ('interaction', 'pharmacology')),
  report_data     JSONB DEFAULT '{}'::jsonb,
  drug_name       TEXT,
  herb_name       TEXT,
  evidence_score  INTEGER,
  evidence_level  TEXT,
  confidence      TEXT,
  created_at      TIMESTAMPTZ DEFAULT now(),

  -- Prevent duplicate saves: one user cannot save the same report twice
  UNIQUE (user_id, report_id)
);

COMMENT ON TABLE saved_reports IS 'User bookmarked/saved reports. Each user can save a given report only once (UNIQUE on user_id + report_id).';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_saved_reports_user_id    ON saved_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_reports_report_id  ON saved_reports(report_id);
CREATE INDEX IF NOT EXISTS idx_saved_reports_type       ON saved_reports(report_type);
CREATE INDEX IF NOT EXISTS idx_saved_reports_created    ON saved_reports(created_at DESC);

-- RLS
ALTER TABLE saved_reports ENABLE ROW LEVEL SECURITY;

-- Users can only read their own saved reports
CREATE POLICY "Users read own saved reports"
  ON saved_reports FOR SELECT
  USING (user_id = auth.uid());

-- Users can only insert their own saved reports
CREATE POLICY "Users insert own saved reports"
  ON saved_reports FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Users can only update their own saved reports
CREATE POLICY "Users update own saved reports"
  ON saved_reports FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Users can only delete their own saved reports
CREATE POLICY "Users delete own saved reports"
  ON saved_reports FOR DELETE
  USING (user_id = auth.uid());


-- ═══════════════════════════════════════════════════════════════════════════════
-- 5. SEARCH_HISTORY
-- ═══════════════════════════════════════════════════════════════════════════════
-- Records every search query made on the platform.
-- user_id is nullable — anonymous searches are stored but users can only
-- retrieve their own history.

CREATE TABLE IF NOT EXISTS search_history (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  query              TEXT NOT NULL,
  engine_type        TEXT,
  drug               TEXT,
  herb               TEXT,
  results_count      INTEGER DEFAULT 0,
  sources_used       JSONB DEFAULT '[]'::jsonb,
  top_citation_count INTEGER DEFAULT 0,
  has_fda_data       BOOLEAN DEFAULT false,
  searched_at        TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE search_history IS 'Search history records. user_id is NULL for anonymous searches. Authenticated users can only see their own history.';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_search_history_user_id     ON search_history(user_id);
CREATE INDEX IF NOT EXISTS idx_search_history_query       ON search_history(query);
CREATE INDEX IF NOT EXISTS idx_search_history_searched_at ON search_history(searched_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_history_engine_type ON search_history(engine_type);

-- RLS
ALTER TABLE search_history ENABLE ROW LEVEL SECURITY;

-- Users can only read their own search history
CREATE POLICY "Users read own search history"
  ON search_history FOR SELECT
  USING (user_id = auth.uid());

-- Authenticated users can insert their own search history;
-- anonymous inserts (user_id IS NULL) are also allowed
CREATE POLICY "Users insert own search history"
  ON search_history FOR INSERT
  WITH CHECK (user_id = auth.uid() OR user_id IS NULL);

-- Users can only update their own search history
CREATE POLICY "Users update own search history"
  ON search_history FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Users can only delete their own search history
CREATE POLICY "Users delete own search history"
  ON search_history FOR DELETE
  USING (user_id = auth.uid());


-- ═══════════════════════════════════════════════════════════════════════════════
-- 6. CACHED_QUERIES
-- ═══════════════════════════════════════════════════════════════════════════════
-- Stores cached API responses to avoid redundant external lookups.
-- Access is restricted to the service role — public users should NOT be able
-- to read or manipulate the cache directly.

CREATE TABLE IF NOT EXISTS cached_queries (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cache_key     TEXT UNIQUE NOT NULL,
  query_type    TEXT,
  query_params  JSONB DEFAULT '{}'::jsonb,
  results       JSONB,
  sources_used  JSONB DEFAULT '[]'::jsonb,
  result_count  INTEGER DEFAULT 0,
  expires_at    TIMESTAMPTZ NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE cached_queries IS 'API response cache. Access restricted to service role only — public users cannot read or write the cache.';

-- Indexes — cache_key already has a unique index from the UNIQUE constraint,
-- but we add a covering index for expiry-based cleanup.
CREATE INDEX IF NOT EXISTS idx_cached_queries_cache_key ON cached_queries(cache_key);
CREATE INDEX IF NOT EXISTS idx_cached_queries_expires_at ON cached_queries(expires_at);
CREATE INDEX IF NOT EXISTS idx_cached_queries_query_type ON cached_queries(query_type);

-- RLS — completely locked down for public access; only service_role can operate
ALTER TABLE cached_queries ENABLE ROW LEVEL SECURITY;

-- No public policies — the table is invisible to anon and authenticated users.
-- All cache operations must go through the Supabase service_role key.
--
-- If you need admin access from the dashboard you can add:
--   CREATE POLICY "Service role full access" ON cached_queries
--     FOR ALL USING (auth.role() = 'service_role')
--     WITH CHECK (auth.role() = 'service_role');
--
-- But by default, service_role bypasses RLS entirely, so no explicit
-- policy is required.


-- ═══════════════════════════════════════════════════════════════════════════════
-- 7. SCIENTIFIC_SYNONYMS
-- ═══════════════════════════════════════════════════════════════════════════════
-- Maps alternate names, brand names, and common misspellings to their
-- canonical scientific term. Used for query normalization so that
-- "warfarin" and "Coumadin" resolve to the same entity.

CREATE TABLE IF NOT EXISTS scientific_synonyms (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  term        TEXT NOT NULL,
  canonical   TEXT NOT NULL,
  term_type   TEXT CHECK (term_type IN ('drug', 'herb', 'compound', 'phytochemical')),
  created_at  TIMESTAMPTZ DEFAULT now(),

  -- Prevent duplicate term+type entries (e.g. two "aspirin" drug rows)
  UNIQUE (term, term_type)
);

COMMENT ON TABLE scientific_synonyms IS 'Synonym lookup table for normalizing drug/herb/compound names to their canonical scientific terms.';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_scientific_synonyms_term       ON scientific_synonyms(term);
CREATE INDEX IF NOT EXISTS idx_scientific_synonyms_canonical  ON scientific_synonyms(canonical);
CREATE INDEX IF NOT EXISTS idx_scientific_synonyms_term_type  ON scientific_synonyms(term_type);
CREATE INDEX IF NOT EXISTS idx_scientific_synonyms_term_type_combo ON scientific_synonyms(term, term_type);

-- RLS — public read-only; only service_role can insert/update/delete
ALTER TABLE scientific_synonyms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read scientific synonyms"
  ON scientific_synonyms FOR SELECT
  USING (true);


-- ═══════════════════════════════════════════════════════════════════════════════
-- TRIGGER: Auto-create user_profile on signup
-- ═══════════════════════════════════════════════════════════════════════════════
-- When a new row is inserted into auth.users (i.e. a user signs up),
-- this trigger automatically creates a corresponding user_profiles row
-- so the application always has profile data to work with.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_profiles (id, email, display_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'display_name', NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1))
  );
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.handle_new_user() IS
  'Trigger function: automatically creates a user_profiles row when a new auth.users row is inserted.';

-- Drop the trigger first if it already exists (idempotent)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- ═══════════════════════════════════════════════════════════════════════════════
-- UTILITY: Clean up expired cache entries
-- ═══════════════════════════════════════════════════════════════════════════════
-- Convenience function to purge stale cached_queries rows.
-- Call periodically (e.g. via pg_cron or a serverless edge function).

CREATE OR REPLACE FUNCTION public.clean_expired_cache()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.cached_queries WHERE expires_at < now();
END;
$$;

COMMENT ON FUNCTION public.clean_expired_cache() IS
  'Utility: deletes all expired rows from cached_queries. Intended to be called periodically.';


-- ═══════════════════════════════════════════════════════════════════════════════
-- END OF SCHEMA v3
-- ═══════════════════════════════════════════════════════════════════════════════
